boardproject/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = "accounts"
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name='logout'),
]

boardproject/boardproject/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views
import home.views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home.views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('photo/', include('photo.urls')),  
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boardproject/photo/urls.py
from django.urls import path
from .views import PhotoMylist, PhotoLike, PhotoList, PhotoDelete, PhotoCreate, PhotoUpdate, PhotoDetail ,PostCountHitDetailView
from . import views

#다른 앱들과 url parttern이름이 겹치는것을 방지하기 위해 사용 
app_name = "photo"
urlpatterns = [
    #함수형 뷰는 이름만 적지만
    #클래스형 뷰는 이름.as_view()로 작성 name은 나중에 불러쓰기 위해 저장
    path("create/", PhotoCreate.as_view(), name='create'),
    path("delete/<int:pk>", PhotoDelete.as_view(), name='delete'),
    path("update/<int:pk>", PhotoUpdate.as_view(), name='update'),
    #detail + 댓글
    #조회수 + detail 함수 연결
    path("detail/<int:pk>", PostCountHitDetailView.as_view(), name='detail'),
    #전체 사진을 보여주는 photolist
    path("",PhotoList.as_view(), name='list'),
    # path("", views.base, name='list'),

    path("like/<int:photo_id>/", PhotoLike.as_view(), name='like'),
    path("mylist/", PhotoMylist.as_view(), name='mylist'),

    #댓글    
    path('comment_add/<int:photo_id>' , views.comment_add, name='comment_add'),
    path('comment_delete/<int:comment_id>' , views.comment_delete, name='comment_delete'),
    path('comment_edit/<int:comment_id>' , views.comment_edit, name='comment_edit'),
]

boardproject/photo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCount, HitCountMixin

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', null=True)
    title = models.CharField(max_length=20 ,null=True)
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='timeline_photo/%Y/%m/%d')  # 알아서 등록날자를 적어
    image2 = models.ImageField(blank=True,null=True, upload_to='timeline_photo/%Y/%m/%d')
    image3 = models.ImageField(blank=True, null=True,upload_to='timeline_photo/%Y/%m/%d')
    hit_count_generic = GenericRelation( HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')

    #크기 줄이는게 아닌데 ?? 
    image_thumbnail = ImageSpecField(source = 'image', processors = [ResizeToFill(300, 300)])
    image_thumbnail = ImageSpecField(source = 'image2', processors = [ResizeToFill(300, 300)])
    image_thumbnail = ImageSpecField(source = 'image3', processors = [ResizeToFill(300, 300)])
    
    #객체가 처음 생성될 때 시간정보 저장
    created = models.DateTimeField(auto_now_add=True, null=True)
    #객체가 저장될 때마다 자동으로 시간 저장
    updated = models.DateTimeField(auto_now=True)

    like = models.ManyToManyField(User, related_name='like_post', blank=True)

    #제목 그래도 출력
    def __str__(self):
        return  self.text

    def summary(self) : 
        return self.text[0:17]

    def len(self) :
        text_len = len(self.text)
        return text_len

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self) : 
        return reverse('photo:detail', args=[self.id])

class Comment(models.Model) : 
    post = models.ForeignKey(Photo, on_delete = models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete = models.CASCADE) 
    body = models.CharField(max_length=500)
    date = models.DateTimeField('date published')
    
    def __str__(self) :
        return self.body

boardproject/photo/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages

from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse

from .models import Photo
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView

from django.contrib.auth.models import User

from django.core.paginator import Paginator

from .models import Photo
from .models import Comment
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from hitcount.views import HitCountDetailView

#mylist
class PhotoMylist(ListView) :
    model = Photo
    template_name = 'photo/photo_mylist.html'

    def dispatch(self, request, *args, **kwargs) :
        #로그인 확인
        if not request.user.is_authenticated :
            messages.warning(request, '로그인을 먼저하세요')
            return HttpResponseRedirect('/')
        return super(PhotoMylist, self).dispatch(request, *args, **kwargs)

#좋아요
class PhotoLike(View) :
    def get(self, request, *args, **kwargs) : 
        #로그인 확인 = 로그인안된 상태이면 자료를 숨김
        if not request.user.is_authenticated : 
            return HttpResponseForbidden()
        else :
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                #이미 좋아요를 누른 상태에서 다시 누르면 좋아요 취소
                if user in photo.like.all():
                    photo.like.remove(user)
                else : 
                    photo.like.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)                 


#class형 뷰의 generic view를 이용하여 구현 
#PhotoList 가장 메인에서 보여줄 로직 
class PhotoList(ListView) : 
    model = Photo
    template_name = 'photo/base.html'
    #한 페이지 그룹의 페이지 수
    paginate_by = 6

    def get_context_data(self, **kwargs):
        global page
        context = super(PhotoList, self).get_context_data(**kwargs)
        paginator = context['paginator']

        #5개씩 잘라서 보여줌
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context

class PhotoCreate(CreateView) : 
    model = Photo
    fields = ['title', 'text' , 'image','image2','image3']
    template_name_suffix = '_create'
    #성공하면 메인 페이지로 이동하기 위해 url을 '/'로 설정
    success_url ='/'
    #user_id확인
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.autor_id = self.request.user.id
        if form.is_valid() :
            #올바르다면
            form.instance.save()
            return redirect('/photo')
        else : 
            #올바르지 않다면
            return self.render_to_response({'form' : form})

class PhotoUpdate(UpdateView) : 
    model = Photo
    fields = ['title', 'text' , 'image','image2','image3']
    template_name_suffix = '_update'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        id = object.id
        if object.author != request.user :
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('')
        else :  
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)
        success_url = ('/photo/detail/' + str(id))

class PhotoDelete(DeleteView) : 
    model = Photo
    template_name_suffix = '_delete'
    success_url ='/photo'

    def dispatch(self, request, *args, **kwargs) : 
        object = self.get_object()
        if object.author != request.user :
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else : 
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoDetail(DetailView) : 
    model = Photo

    def get_context_data(self, **kwargs):
        context = super(PhotoDetail, self).get_context_data(**kwargs)
        context['photo_list'] = Photo.objects.all()
        return context

class PostCountHitDetailView(PhotoDetail, HitCountDetailView):
    """
    Generic hitcount class based view that will also perform the hitcount logic.
    """
    count_hit = True

@login_required
def comment_add(request, photo_id) :
    if request.method == "POST" :
        post = get_object_or_404(Photo, pk=photo_id)
        comment = Comment()
        comment.user = request.user
        comment.body = request.POST['body']
        comment.post = post
        comment.date = timezone.now()
        comment.save()
        return redirect('/photo/detail/' + str(photo_id))
    else :
        return HttpResponse('잘못된 접근입니다.')


def comment_edit(request, comment_id) : 
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.user :
        if request.method == "POST" :
            comment.body = request.POST['body']
            comment.save()
            return redirect('/photo/detail/' + str(comment.post.id))
        elif request.method == "GET" :
            context ={
                'comment' : comment
            }  
            return render(request, 'photo/comment_edit.html', context)
    else :
        return HttpResponse('잘못된 접근입니다.')


def comment_delete(request, comment_id) :
    comment = get_object_or_404(Comment, pk = comment_id)
    if request.user == comment.user:
        if request.method == "POST": 
            comment.delete()
            return redirect('/photo/detail/' +str(comment.post.id ))
    return HttpResponse('잘못된 접근입니다.')

boardproject/templates/photo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <title>Board</title>
    <style>
    footer {
    padding-bottom: 10vh;
    padding-top: 30vh;
}

.footer {
    width: 100%;
    height: 120px;
    display: -webkit-flex;
    display: flex;
}

.item {
    margin: 10px;
    color: rgb(180, 151, 151);
    font-size: 13px;
    text-align: left;
    line-height: 20px;
}

.item:nth-child(1) {
    -webkit-flex: 3;
    flex: 1;
}

.item:nth-child(2) {
    -webkit-flex: 1;
    flex: 2;
}

.item:nth-child(3) {
    -webkit-flex: 1;
    flex: 1;
    text-align: right;
}

.item_b {
    font-weight: bolder;
    size: 15px;
    line-height: 15px;
}

.top {
    font-size: 20px;
    position: fixed;
    right: 20px;
    bottom: 20px;
    width: 30px;
    height: 30px;
    background: rgba(240, 164, 255, 0.5);
    /* border-radius: 50%; */
    color: #fff;
    text-decoration: none;
    cursor: pointer;
    text-align: center;
    line-height: 30px;
}</style>

</head>

<body>
    <div id="wrap">
        <div id="hearder_wrap">
            <div class="hearder_container">
                <div class="logo">
                    <a href="{% url 'home' %}"></a>
                </div>
                <nav>
                    <ul>
                        <li><a class="" href="{% url 'home' %}">Home</li>
                        <li><a class="" href="{% url 'photo:list' %}">Board</li>
                        {%if user.is_authenticated%}
                        <li><a href="#">{{user.username}}</a></li>
                        <li><a href="{% url 'photo:create' %}">사진 올리기</a></li>
                        <li><a href="{% url 'photo:mylist' %}">내사진 리스트</a></li>
                        <li><a href="javascript:{document.getElementById('logout').submit()}">Logout</a></li>
                        <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
                            {% csrf_token %} <input type="hidden" />
                        </form>
                    </ul>

                </nav>
                {%else%}
                <li><a href="{%url 'accounts:login'%}">Login</a></li>
                <li><a href="{%url 'accounts:signup'%}">회원가입</a></li>
                {%endif%}

            </div>
        </div>
        <div id="content_wrap">
            <div class="content_container">
                {% for object in object_list %}
                <!-- <div class="content_container"> -->
                <div class="card">
                    <div class="card_header">
                        <div class="title">
                            <h3>{{object.title}}</h3>
                        </div>
                        <div class="author">
                            <h3>{{object.author}}</h3>
                        </div>
                    </div>
                    <div class="image-wrapper">
                        <div class="thumbnail">
                            <div class="center">
                                <img src=" {{ object.image.url }}" style="height: auto" ; width="auto" ; alt="사진">
                            </div>
                        </div>
                    </div>
                    <div class="card_body">
                        <p>
                            {{ object.summary }}
                            <!-- 문자열 길이 -->
                            {% if object.len > 17 %}
                            <a href="{% url 'photo:detail' object.id %}">..more</a>
                            {% endif %}
                        </p>
                    </div>
                    <ul class="list">
                        <li class="list_item"><a href="{%url 'photo:like' object.id %}"
                                class="btn_like {%if user in object.like.all %} active {%endif%} "> 좋아요</a>
                            <!-- 좋아요 수 출력 -->
                            {%if object.like.all.count == 0%}
                            <b>0</b>
                            {%elif object.like.all.count%}
                            <b>{{object.like.all.count}}</b>
                            {%endif%}
                        </li>
                        <li>생성일 : {{ object.created|date:'Y.m.d H:i'}}</li>
                        <!-- <li>수정일 : {{ object.updated }}</li> -->
                    </ul>
                    <div class="card_body">
                        <a href="{% url 'photo:detail' object.id %}">본문보기</a>

                        <!-- 권한 확인 -->
                        {% if user == object.author %}
                        <a href="{% url 'photo:update' object.id %}">수정하기</a>
                        <a href="{% url 'photo:delete' object.id %}">삭제하기</a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- Pagination -->
            <div class="paginator_container">
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}">
                                <span>
                                    < </span> </a> </li> {% else %} <li class="disabled" style="display: none">
                                        <a href="#">
                                            <span>
                                                < </span> </a> </li> {% endif %} {% for page in page_range %} <li
                                                    {% if page == page_obj.number %} class="_active" {% endif %}>
                                                    <a href="?page={{ page }}">{{ page }}</a>
                        </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}">
                                <span> > </span>
                            </a>
                        </li>
                        {% else %}
                        <li {% if not page_obj.has_next %}class="disabled" {% endif %}>
                            <a href="#">
                                <span> > </span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <!-- Pagination -->
        </div>
    </div>
    <footer>
        <div class="footer">
                <div class="item">
                    <img src='../../static/images/han_turtle.png' style="width: 100px; height:100px;" alt="한터틀">
                </div>
                <div class="item">
                    <p>
        
        (주)한터틀 | 대표이사 : 한지원 |
        주소 : 광주광역시 동구 필문대로 309 
        <br><br>
        사업자등록번호:123456789 | 통신판매신고 : age21summer |
        <h7>copyright(c) 2019 all right reserved</h7>
                </p>
                </div>
                <div class="item">
                    <div class='item_b'> BO SNS</div>
                    유튜브 | 블로그 | 인스타그램
                    <div class='item_b'>고객센터</div>
                    평일 : 9:00-18:30
                    <div class='item_b'>1:1상담</div>
                    누가할래?난 안해
                </div>
            </div>

</footer>

</body>

</html>

boardproject/templates/photo/comment_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/comment_edit.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <title>Board</title>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>

</head>

<body>
    <div id="wrap">
        <div id="hearder_wrap">
            <div class="hearder_container">
                <div class="logo">
                    <a href=""></a>
                </div>
                <nav>
                    <ul>
                        <li><a class="" href="{% url 'home' %}">Home</li>
                        {%if user.is_authenticated%}
                        <li><a href="#">{{user.username}}</a></li>
                        <li><a href="{% url 'photo:create' %}">사진 올리기</a></li>
                        <li><a href="{% url 'photo:mylist' %}">내사진 리스트</a></li>
                        <li><a href="javascript:{document.getElementById('logout').submit()}">Logout</a></li>
                        <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
                            {% csrf_token %} <input type="hidden" />
                        </form>
                    </ul>

                </nav>
                {%else%}
                <li><a href="{%url 'accounts:login'%}">Login</a></li>
                <li><a href="{%url 'accounts:signup'%}">회원가입</a></li>
                {%endif%}

                {%if message %}
                {%for message in messages %}
                <p>{{message}}</p>
                {%endfor%}
                {%endif%}

            </div>
        </div>
        <div id="content_wrap">
            <div class="content_container">
                <div class="comment_area">
                    <div class="comment_box">
                        <label for="">댓글 수정</label>
                        <form id="edit" action="{% url 'photo:comment_edit' comment.id %}" method="POST">
                            {% csrf_token %}
                            <textarea rows=8 cols=40 name="body">{{comment.body}}</textarea>
                            <div class="cmt_btn">
                                <button onclick="goBack()">돌아가기</button>
                                <input id="edit" type="submit" value="수정">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div id="footer_wrap">
            <div class="footer_container">
                footer_container
            </div>
        </div>
    </div>
</body>

</html>

boardproject/templates/photo/photo_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <title>Board</title>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
    <style>
    footer {
    padding-bottom: 10vh;
    padding-top: 30vh;
}

.footer {
    width: 100%;
    height: 120px;
    display: -webkit-flex;
    display: flex;
}

.item {
    margin: 10px;
    color: rgb(180, 151, 151);
    font-size: 13px;
    text-align: left;
    line-height: 20px;
}

.item:nth-child(1) {
    -webkit-flex: 3;
    flex: 1;
}

.item:nth-child(2) {
    -webkit-flex: 1;
    flex: 2;
}

.item:nth-child(3) {
    -webkit-flex: 1;
    flex: 1;
    text-align: right;
}

.item_b {
    font-weight: bolder;
    size: 15px;
    line-height: 15px;
}

.top {
    font-size: 20px;
    position: fixed;
    right: 20px;
    bottom: 20px;
    width: 30px;
    height: 30px;
    background: rgba(240, 164, 255, 0.5);
    /* border-radius: 50%; */
    color: #fff;
    text-decoration: none;
    cursor: pointer;
    text-align: center;
    line-height: 30px;
}</style>

</head>

<body>
    <div id="wrap">
        <div id="hearder_wrap">
            <div class="hearder_container">
                <div class="logo">
                    <a href=""></a>
                </div>
                <nav>
                    <ul>
                        <li><a class="" href="{% url 'home' %}">Home</li>
                        {%if user.is_authenticated%}
                        <li><a href="#">{{user.username}}</a></li>
                        <li><a href="{% url 'photo:create' %}">사진 올리기</a></li>
                        <li><a href="{% url 'photo:mylist' %}">내사진 리스트</a></li>
                        <li><a href="javascript:{document.getElementById('logout').submit()}">Logout</a></li>
                        <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
                            {% csrf_token %} <input type="hidden" />
                        </form>
                    </ul>

                </nav>
                {%else%}
                <li><a href="{%url 'accounts:login'%}">Login</a></li>
                <li><a href="{%url 'accounts:signup'%}">회원가입</a></li>
                {%endif%}

                {%if message %}
                {%for message in messages %}
                <p>{{message}}</p>
                {%endfor%}
                {%endif%}

            </div>
        </div>
        <div id="content_wrap">
            <div class="content_container">
                <!-- 제목 및 아이디 조회수, 좋아요 -->
                <div class="conetent_head">
                    <div class="area">
                        <div class="top_area">
                            <div class="title">
                                {{object.title}}
                            </div>
                            <div class="time">
                                {{object.created|date:'Y.m.d H:i'}}
                            </div>
                        </div>
                        <div class="bot_area">
                            <div class="author">
                                {{object.author}}
                            </div>
                            <div class="right_side">
                                <span>
                                    <b>조회수 : {{ hitcount.total_hits }} </b>
                                </span>
                                <span>좋아요
                                    {%if object.like.all.count == 0%}
                                    <b>0</b>
                                    {%elif object.like.all.count%}
                                    <b>{{object.like.all.count}}</b>
                                    {%endif%}
                                </span>
                                <span>댓글
                                    <b>{{object.comments.all.count}}</b>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- 제목 및 아이디 조회수, 좋아요 -->

                <!-- 사진 및 내용 -->
                <div class="content_body">
                    <div class="content_area">
                        <p><img src="{{ object.image.url }}" alt="post_image">
                        </p>
                        {%if object.image2.url != null %}
                        <p><img src="{{ object.image2.url }}" alt="post_image">
                        </p>{%endif%}
                        {%if object.image3.url != null %}
                        <p><img src="{{ object.image3.url }}" alt="post_image">
                        </p>{%endif%}
                        <p>{{ object.text }}</p>
                    </div>
                    <!-- 좋아요 버튼 -->
                    <div class="content_btn">
                        <a href="{%url 'photo:like' object.id%}">
                            <div class="btn_like {%if user in object.like.all%} active {%endif%}">
                                좋아요
                            </div>
                        </a>
                        {%if object.like.all.count == 0%}
                        <b>0</b>
                        {%elif object.like.all.count%}
                        <b>{{object.like.all.count}}</b>
                        {%endif%}

                        <div class="btn_">
                            <a href="{% url 'photo:list' %}"><input type="button" value="목록"></a>
                            {% if user == object.author %}
                            <a href="{% url 'photo:update' object.id %}"><input type="submit" value="수정"></a>
                            <a href="{% url 'photo:delete' object.id %}"><input type="submit" value="삭제"></a>

                            {% endif %}
                        </div>
                    </div>

                    <!-- 댓글 -->
                    <div class="comment_area">
                        <div class="comment_head">
                            <div class="tag">
                                <b>Comments '{{object.comments.all.count}}' </b>
                            </div>
                            <ul class="comment_ul">
                                <!-- comment 갯수만큼 li생성 -->
                                {% for comment in object.comments.all%}
                                <li class="comment_list">
                                    <!-- meta는 댓글 글쓴이 정보 -->
                                    <div class="meta">
                                        <p>{{comment.user.username}}</p>
                                        <p>{{comment.date|date:'Y.m.d H:i'}}</p>
                                    </div>
                                    <!-- 댓글 글쓴이라면 수정 삭제 -->
                                    {% if user == comment.user %}
                                    <div class="hover_nav">
                                        <a href="{% url 'photo:comment_edit' comment.id %}">수정</a>
                                        <a href="#">댓글</a>
                                        <a href="javascript:{var form=document.getElementById('delete');
                                        form.action='/photo/comment_delete/{{comment.id}}';
                                        form.submit();}">삭제</a>
                                        <form id="delete" method="POST" action="">
                                            {% csrf_token %}<input type="hidden"> </form>
                                    </div>
                                    {%else%}
                                    <div class="hover_nav">
                                        <a href="#">댓글</a>
                                    </div>
                                    {%endif%}
                                    <div class="comment">
                                        <p>{{comment.body}}</p>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="comment_box">
                            <label for="">댓글쓰기</label>
                            <form id="add" action="{% url 'photo:comment_add' object.id %}" method="POST">
                                {% csrf_token %}
                                <textarea rows=8 cols=40 name="body"></textarea>
                                <div class="cmt_btn">
                                    <input id="add" type="submit" value="등록">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer>
            <div class="footer">
                    <div class="item">
                        <img src='../../static/images/han_turtle.png' style="width: 100px; height:100px;" alt="사진">
                    </div>
                    <div class="item">
                        <p>
            
            (주)팀이름 | 대표이사들 : 강상혁 김은영 마서연 박효빈 한지원 |
            주소 : 광주광역시 동구 필문대로 309 
            <br><br>
            사업자등록번호:123456789 | 통신판매신고 : 132광주4752 |
            <h7>copyright(c) 2019 all right reserved</h7>
                    </p>
                    </div>
                    <div class="item">
                        <div class='item_b'> BO SNS</div>
                        유튜브 | 블로그 | 인스타그램
                        <div class='item_b'>고객센터</div>
                        평일 : 9:00-18:30
                        <div class='item_b'>1:1상담</div>
                        누가할래?난 안해
                    </div>
                </div>

    </footer>
    </div>
    </div>

</body>

</html>

boardproject/templates/photo/photo_mylist.html
<!-- 모든 게시글 리스트에서 
    게시글의 글쓴이와 로그인유저가 같은지 비교 -->
    {% for object in object_list %}
    {% if object.author == user %}
    <img src="{{object.image.url}}" alt="image">
    <!-- object.image_thumbnail.url  -->
    {% endif %}
    {% endfor %}